// <auto-generated />
using System;
using System.Collections;
using APB.AccessControl.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APB.AccessControl.DataAccess.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20250404212327_fix2")]
    partial class fix2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessGrid", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EmployeeId", "AccessGroupId");

                    b.HasIndex("AccessGroupId");

                    b.ToTable("AccessGrids");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AccessGroups");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessPointId")
                        .HasColumnType("integer");

                    b.Property<string>("AccessResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateAccess")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointId");

                    b.HasIndex("CardHash");

                    b.HasIndex("CardId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPointTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointTypeId");

                    b.ToTable("AccessPoints");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessPointType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessPointTypes");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AccessPointId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("AllowedTimeEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("AllowedTimeStart")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<BitArray>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("bit(7)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecificDates")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("AccessPointId");

                    b.ToTable("AccessRules");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessTriggerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessLogId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessLogId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExecutionResult")
                        .HasColumnType("boolean");

                    b.Property<int>("TriggerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessLogId");

                    b.HasIndex("AccessLogId1");

                    b.HasIndex("TriggerId");

                    b.ToTable("AccessTriggerLogs");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatronymicName")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPointId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShowOnPass")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessPointId")
                        .HasColumnType("integer");

                    b.Property<string>("AccessResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessGrid", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessGroup", "AccessGroup")
                        .WithMany("AccessGrids")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APB.AccessControl.Domain.Entities.Employee", "Employee")
                        .WithMany("AccessGrids")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("AccessLogs")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APB.AccessControl.Domain.Entities.Card", "Card")
                        .WithMany("AccessLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("APB.AccessControl.Domain.Entities.Employee", "Employee")
                        .WithMany("AccessLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AccessPoint");

                    b.Navigation("Card");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessPoint", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessPointType", "AccessPointType")
                        .WithMany("AccessPoints")
                        .HasForeignKey("AccessPointTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessPointType");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessRule", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessGroup", "AccessGroup")
                        .WithMany("AccessRules")
                        .HasForeignKey("AccessGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APB.AccessControl.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("AccessRules")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessGroup");

                    b.Navigation("AccessPoint");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessTriggerLog", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessLog", "AccessLog")
                        .WithMany()
                        .HasForeignKey("AccessLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APB.AccessControl.Domain.Entities.AccessLog", null)
                        .WithMany("AccessLogTriggers")
                        .HasForeignKey("AccessLogId1");

                    b.HasOne("APB.AccessControl.Domain.Entities.Trigger", "Trigger")
                        .WithMany("AccessTriggerLogs")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLog");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Card", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.Employee", "Employee")
                        .WithMany("Cards")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Notification", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("Notifications")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APB.AccessControl.Domain.Entities.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AccessPoint");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Trigger", b =>
                {
                    b.HasOne("APB.AccessControl.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("Triggers")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessPoint");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessGroup", b =>
                {
                    b.Navigation("AccessGrids");

                    b.Navigation("AccessRules");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessLog", b =>
                {
                    b.Navigation("AccessLogTriggers");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessPoint", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("AccessRules");

                    b.Navigation("Notifications");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.AccessPointType", b =>
                {
                    b.Navigation("AccessPoints");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Card", b =>
                {
                    b.Navigation("AccessLogs");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AccessGrids");

                    b.Navigation("AccessLogs");

                    b.Navigation("Cards");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("APB.AccessControl.Domain.Entities.Trigger", b =>
                {
                    b.Navigation("AccessTriggerLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
